### PR TITLE
Feat: Implement four and two players waiting room screen 

### PR DESCRIPTION
**Pull request by codeZe-us**
This PR:
1. Holds waiting room screens and functionality for two, three and four players.
Screenshot 2024-12-01 at 02 29 49

### CODE REVIEW

**Comment by codeZe-us** [comment]
@wms2537 please check this out for corrections

**Comment by codeZe-us** [comment]
@gianalarcon @wms2537 @wms2537 please review

**Comment by wms2537** [comment]
image
Lets make the invite option available for every empty box

**Comment by wms2537** [comment]
And also now the right top menu button directly returns to home, instead it should return to the previous menu screen (where user can select resume or exit game)

**Comment by codeZe-us** [comment]
> And also now the right top menu button directly returns to home, instead it should return to the previous menu screen (where user can select resume or exit game)

Okay.

**Comment by codeZe-us** [comment]
Screenshot 2024-12-01 at 13 12 32
@wms2537 @gianalarcon please review

**Review by wms2537 — APPROVED** [review]
Nice job! Looks good!

**Pull request merged**
