### PR TITLE
feat: Implement create game module

### PR DESCRIPTION
**Pull request by codeZe-us**
This PR:
1. Implement Checkers create game screen module.
2. Implement folder structure.
3. Implement reusable components.

Screen record link:  https://drive.google.com/file/d/1fOkODlR8HLGqm_GVKFQ56eg3qJlDXhvC/view?usp=drive_link

### CODE REVIEW

**Comment by co01y4p** [comment]
@codeZe-us Hi
Checked the work on branch _branch-od11_

The game welcome screen looked ok, create game flow is there, find game/ join game dummy flow is there.

One thing to mention: 
the screen let user to input how much value of token, we are hoping for a manual input. Please see below image

**Comment by co01y4p** [comment]
@codeZe-us Hi
Checked the work on branch branch-od11

The game welcome screen looked ok, create game flow is there, find game/ join game dummy flow is there.

One thing to mention:
the screen let user to input how much value of token, we are hoping for a manual input. Please see below image

current:
Screenshot 2024-12-15 at 17 32 13

the one we hoping/ implementing in Ludo
Screenshot 2024-12-15 at 17 39 56


Let us know if there is any clarification needed.

**Comment by codeZe-us** [comment]
> @codeZe-us Hi Checked the work on branch branch-od11
> 
> The game welcome screen looked ok, create game flow is there, find game/ join game dummy flow is there.
> 
> One thing to mention: the screen let user to input how much value of token, we are hoping for a manual input. Please see below image
> 
> current: Screenshot 2024-12-15 at 17 32 13
> 
> the one we hoping/ implementing in Ludo Screenshot 2024-12-15 at 17 39 56
> 
> Let us know if there is any clarification needed.

@co01y4p Okay, i didn't see that on the design though, but yeah, I will add it.

**Comment by codeZe-us** [comment]
@co01y4p Done
Screenshot 2024-12-15 at 13 30 35
Screenshot 2024-12-15 at 13 31 31
Screenshot 2024-12-15 at 13 29 59

**Comment by co01y4p** [comment]
Helo @codeZe-us 

https://github.com/user-attachments/assets/033e6715-dac8-4cbc-8f05-31aa772bb287

everything looked ok for me, except 1 glitch i found
In short, when user enter the value which is = 0, or value that greater than available amount, the Text cursor will missing after user's input, in which, i believe is the keyboard in app will gone too.

Uploading Screen Recording 2024-12-15 at 21.33.32.mov…

secondly, about the overflow issue when keyboard is appeared.

Thank you!

**Comment by codeZe-us** [comment]
@co01y4p Fixed. Also the keyboard issue is fixed, please confirm from your end

https://github.com/user-attachments/assets/95bd9623-0b65-47d0-8512-7e4bf987968d

**Comment by co01y4p** [comment]
@codeZe-us Helo!

OK, i verified latest 2 issues have addressed.

Thank you so much.

**Review by co01y4p — APPROVED** [review]
OK approved. cc @wms2537

**Comment by gianalarcon** [comment]
@codeZe-us pls just fix the recent conflict, then we will be able to merge

**Comment by codeZe-us** [comment]
> @codeZe-us pls just fix the recent conflict, then we will be able to merge

@gianalarcon ok

**Comment by codeZe-us** [comment]
@gianalarcon done

**Pull request merged**
