### PR TITLE
fix: Fix responsiveness issue

### PR DESCRIPTION
**Pull request by codeZe-us**
This PR:
Fixed responsiveness issues for different screen sizes.

Screenshot 2024-12-17 at 11 38 01

Screenshot 2024-12-17 at 11 50 40

Screenshot 2024-12-17 at 11 52 14

### CODE REVIEW

**Comment by wms2537** [comment]
Have you tried it on tablets?

**Comment by wms2537** [comment]
Here are a list of device sizes required to be tested out
```
final testDevices = [
  const Device(
    name: "Screen_Android",
    size: Size(369, 656),
    textScale: 1,
    devicePixelRatio: 1,
  ),
  const Device(
    name: "Screen_AndroidTablet7Inch",
    size: Size(603, 1072),
    textScale: 1,
    devicePixelRatio: 1,
  ),
  const Device(
    name: "Screen_AndroidTablet10Inch",
    size: Size(1080, 1920),
    textScale: 1,
    devicePixelRatio: 1,
  ),
  const Device(
    name: "Screen_IpadPro13Inch",
    size: Size(2064 / 2, 2752 / 2),
    textScale: 2,
    devicePixelRatio: 2,
  ),
  const Device(
    name: "Screen_Iphone6Inch9",
    size: Size(1320 / 2, 2868 / 2),
    textScale: 2,
    devicePixelRatio: 2,
  ),
];
```
I also noticed that we are using a lot of hardcoded values. This is ok if we are wrapping another `Transform.scale` widget to scale it accordingly to the game size. But since now the create game screen is designed as a separate screen pushed using the `Navigator`, I think it is better to make it adaptive?

**Comment by codeZe-us** [comment]
@wms2537 oK

**Comment by gianalarcon** [comment]
Hi Sir, could you manage to finish this PR anytime soon pls?

**Comment by codeZe-us** [comment]
> Hi Sir, could you manage to finish this PR anytime soon pls?

@gianalarcon yeah, will complete it today

**Comment by codeZe-us** [comment]
@wms2537 please review 
Screenshot 2024-12-19 at 21 14 10
Screenshot 2024-12-19 at 21 14 47
Screenshot 2024-12-19 at 21 14 53
Screenshot 2024-12-19 at 21 15 22
Screenshot 2024-12-19 at 21 15 56
Screenshot 2024-12-19 at 21 16 05
Screenshot 2024-12-19 at 21 16 09
Screenshot 2024-12-19 at 21 16 19

**Review by wms2537 — APPROVED** [review]
Approved

**Pull request merged**
