### PR TITLE
Update create game section #19

### LINKED ISSUE #19: Update `create game` section
## Issue Overview

`Create game` section is missing a manual enter token field

## Proposed Solutions or Ideas

- Implement this section based on provided [design](https://www.figma.com/design/bnuIyw9uQSTdWTJ273WUgn/The-Marquis-Mobile-App-Only-Dust?node-id=4554-6476&node-type=canvas&t=4NugNRwW3ZYeNlXZ-0)
image

- Make sure integration and previous functionality works

### PR DESCRIPTION
**Pull request by Emrys02**
[Loom Screen Recording Link](https://www.loom.com/share/6141d55c44b34b9298e0aab78fc887bb?sid=c690eb93-817a-4e57-8443-7f640d3bfde8)

Closes #19 

### Changes Made

- Added support for manual entry of token amount.
- Changed BG color of currently selected token

### CODE REVIEW

**Comment by co01y4p** [comment]
@Emrys02 
Hi there!

For the manual entry of token amount, we expecting a validation such that any number greater than the available amount, shall not let user to press 'next' / proceed to next section

For the changed BG color of currently selected token, may i double check with you, which changes you did for such?

Thankyou!

**Comment by Emrys02** [comment]
@co01y4p

The bug previously allowing user to proceed after entering a value higher than the wallet balance or 0 has been addressed. 


The previous background colour of a selected token was a gradient but the design has a solid colour. That's the change. The size was also increased reflecting the larger button size in the design.

**Comment by co01y4p** [comment]
@Emrys02 

Hi there! 
Previously was only a slider for user to input, which quite impossible, to have any value, greater than maximum amount of the balance.
The manual entry of token, then, only introduced this new possible issue.

Quick hint, You may want to try the textFormatter method.

Thank you!

**Comment by Emrys02** [comment]
@co01y4p 

You're right the problem was due to a lack of proper handling when an invalid amount is introduced by the presence of the manual input. The last commit made has resolved the issue by disabling the next until a valid amount is entered.

**Comment by co01y4p** [comment]
@Emrys02 

Helo! I'm sorry that i oversee the statement you addressed that you solved.

I had verified the 2 changes:
   - Added support for manual entry of token amount.
   - Changed BG color of currently selected token
are working ok.

Thank you for your work @Emrys02  !

**Review by co01y4p — APPROVED** [review]
Verified. Good to go. cc @wms2537

**Pull request merged**
