### PR TITLE
Mobile App: Fix Enter OTP view and Implement new UI

### PR DESCRIPTION
**Pull request by Hoossayn**
## This PR:
-  updated auth dialog
- validate email
- update otp dialog 
- fixed otp box not clearing input on back button pressed
- save Qr code to device 
- update home screen UI
- update profile screen UI

## Demo video
https://www.loom.com/share/8e1239fa785c45dcb77d40e4702f152a

### CODE REVIEW

**Comment by gianalarcon** [comment]
Great job @Hoossayn ,in case you face some issues you can leave it here or on discord. cc: @wms2537 @co01y4p

**Comment by gianalarcon** [comment]
Hi @Hoossayn. Checking in on your progress. Let me know if you're blocked.

**Comment by Hoossayn** [comment]
> Hi @Hoossayn. Checking in on your progress. Let me know if you're blocked.

Hi @gianalarcon Not blocked, just had a busy weekend

**Comment by gianalarcon** [comment]
Great job @Hoossayn, just missing few new sections based on new desing 
image

Currently we just support read balance for STRK and ETH. Every new user will get 0 STRK and around ~ 0.0008ETH

**Comment by gianalarcon** [comment]
Profile view also need to be updated
image

Please check issue description to make sure you implementing all required new views

**Comment by gianalarcon** [comment]
@Hoossayn if PR is ready please update your loom video. Thank you so much

**Comment by Hoossayn** [comment]
> @Hoossayn if PR is ready please update your loom video. Thank you so much

@gianalarcon updated loom video

**Comment by gianalarcon** [comment]
Awesome! Looks good, Just need to read the balance for STRK and ETH
image
Every new user will get 0 STRK and around ~ 0.0008ETH
Need to see the 0.0008ETH there
and also trasnfer some sepolia STRK to that account so we can see the ETH balance as well

**Comment by gianalarcon** [comment]
Almost done! Make sure you added the `BROTHER` token
image

**Comment by co01y4p** [comment]
@Hoossayn Great job! The overall functionality is working as expected! 
However there are some slight adjustments:

1. All the Token's Name appeared in the appbar, should be same font size (current one STRK is slightly bigger)

2. All the token in that appbar, should have same width (current one wider on longer name)

3. Missing out some blue separator vertical bar, on the left and right of the _show/hide_ button

4. The background of the home page seemed not changing based on the overall width of the screen (see photo below)
Screenshot 2024-11-27 at 00 43 33

**Comment by Hoossayn** [comment]
> 1. appeared

@co01y4p  Fixed all other issues. 
For No.2 I made the width dynamic because token balance will get truncated and i wasn't sure if we want that. for example 0.000893289 will become 0.0008... 

Kindly let me know if with the above explanation you still want me to make the width static. I'd make the changes. Thanks

**Comment by wms2537** [comment]
Can consider making the text size smaller to fit in

**Comment by wms2537** [comment]
And also may I know the point of using the screenshots package? Since we can directly get the qr image bytes through the QR image view?

**Comment by Hoossayn** [comment]
> And also may I know the point of using the screenshots package? Since we can directly get the qr image bytes through the QR image view?

QrImageView does not have any exposed method to get the image bytes

**Comment by wms2537** [comment]
We have a function to convert widget to image in 
https://github.com/The-Marquis-Gaming/themarquis-app/blob/95ceb3dc13cf57633603817d5796f7e1b5f32c17/lib/screens/profile_screen.dart#L446

**Comment by Hoossayn** [comment]
> We have a function to convert widget to image in
> 
> https://github.com/The-Marquis-Gaming/themarquis-app/blob/95ceb3dc13cf57633603817d5796f7e1b5f32c17/lib/screens/profile_screen.dart#L446

@wms2537 Done!

**Review by wms2537 — APPROVED** [review]
Looks good! Can merge.

**Pull request merged**
