### PR TITLE
Modifying Ludo Ui design

### PR DESCRIPTION
**Pull request by akintewe**
Currently modifying the UI according to the figma.

Loom Video

https://www.loom.com/share/aa8ae9b7370444b991c81856093b6809?sid=d9fea85f-e187-4041-939b-bbb243e2ae53

### CODE REVIEW

**Comment by gianalarcon** [comment]
Please also add a short loom video. Thanks!

**Comment by akintewe** [comment]
> Please also add a short loom video. Thanks!

no problem thank you

**Comment by gianalarcon** [comment]
Awesome
Missing these views and few more, please check with the provided figma
image

**Comment by akintewe** [comment]
> Awesome Missing these views and few more, please check with the provided figma image

alright no problem, thank you

**Comment by akintewe** [comment]
updated screens 

Loom video:


https://www.loom.com/share/82793536a556479e844f97ba5d4c13ff?sid=3e02c306-0664-4eb2-bd41-607a810bff23

**Comment by gianalarcon** [comment]
Great job. 
Please match with figma as much as possible. In the below pic I just spotted few mismatches, there are more on that view
image

**Comment by gianalarcon** [comment]
Here as well, design should be me same as figma 
image

**Comment by gianalarcon** [comment]
Missing error messages 
image

**Comment by gianalarcon** [comment]
Missing animation of "roll dice" and message in case you dont get 6 in order to leave the basement 
image

**Comment by akintewe** [comment]
Please check the modified changes.   

Video:

https://www.loom.com/share/0a4a3dc50dbb4f63bace8f3d4701fc05?sid=9bf9149b-b763-490f-af11-186ef47dac16. 


based on the messages below i created components for them that will be used based on the play state

**Comment by akintewe** [comment]
> Missing error messages image

done, created components for them

**Comment by akintewe** [comment]
Updated ui and added dice animation with game over screen full video 

https://www.loom.com/share/a04a816b7e1846c29455b5a9a2de23f8?sid=3ef4d0d3-5a4b-41c2-9664-b5a1a0f837f3

**Comment by co01y4p** [comment]
Hi @akintewe 
We found few problems on it.

1. the result page, displaying all player with respective gain/loss, is still quite different from Figma design

Your commits:
Screenshot 2024-11-30 at 00 07 17
Figma design:
Screenshot 2024-11-30 at 00 09 31

**Comment by akintewe** [comment]
> Hi @akintewe We found few problems on it.
> 
> 1. the result page, displaying all player with respective gain/loss, is still quite different from Figma design
> 
> Your commits: Screenshot 2024-11-30 at 00 07 17 Figma design: Screenshot 2024-11-30 at 00 09 31

Ok noted, will modify

**Comment by akintewe** [comment]
@co01y4p  please review the modified changes


https://www.loom.com/share/3624399cae1b43faa8460117f329ea60?sid=db36d70e-8a30-4a34-a2e8-a11b55fe5749

**Review by co01y4p — APPROVED** [review]
Looks OK to us. Thank you!

**Pull request merged**
