### PR TITLE
Completed UI Changes on Pre Game Screen

### PR DESCRIPTION
**Pull request by Emrys02**
The recent changes on the create game screen we're also implemented.

### CODE REVIEW

**Comment by Emrys02** [comment]
https://www.loom.com/share/687119f1d3ea4bedb220819b6d314981?sid=47e3618c-2ef4-4809-bda7-190def6f0208

**Comment by wms2537** [comment]
Manage the balance visibility in the appState, use the `state` of the provider to manage it, so that we can listen to changes with ref.watch in the widget tree easier. Or if can better manage the widget state in the widget, don't use provider.

**Comment by wms2537** [comment]
We have some updates on the stepper side, only display the active step

**Comment by Emrys02** [comment]
Balance visibility is now being managed in the `appStateProvider` rather than the previously used `userProvider`.

I persisted with using a provider to maintain the state across the app rather than limiting it to an instance of the widget

**Comment by Emrys02** [comment]
image

If this is what you mean, it has already been implemented. Check it out using the loom link previously sent

**Comment by Emrys02** [comment]
[New Link for Updated UI](https://www.loom.com/share/c63cacab4e544447ac768b57fde806c3?sid=db670bd6-e179-4bb1-a362-a8ea8faf3776)



image

Photo was taken after the recording. The change is the active selection text color.

**Comment by co01y4p** [comment]
@Emrys02 Hi there!
Few quick problems we spotted:


1. the overflow issue on all page/ sub-pages, also the  icon and button text appeared to be smaller than expected. can try make it dynamic? 
Screenshot 2024-11-29 at 23 47 42

2. the pin behaviour wrong. Before user click anything, the "Next" button should be disabled. After user choose the color, there should be an indicator that which color is chose, then the "next" button only enabled. Please make sure when user back from next page (summary page -> back to choose color), the chosen color indicator still there.
Screenshot 2024-11-29 at 23 48 59
Below show the white indicator on which color user chose.:
Screenshot 2024-11-29 at 23 54 34

3. button text mis-alligned, should be center and consistent as other screen's button.
Screenshot 2024-11-29 at 23 49 59

 4. for all the button , the "selected" effect did not change the color of the button text, WHILE the background gradient is not creating strong contrast (i.e. the center part is not dark enough), resulting the cyan blue text crash with the "selected effect" button background. Please change to expected design. Below show the figma design.
Screenshot 2024-11-29 at 23 56 35


Thank you! cc @wms2537

**Comment by Emrys02** [comment]
All the raised issues have been addressed

**Comment by co01y4p** [comment]
Hi @Emrys02 ,

everything looked good , **except** the issue (4) highlighted, about the "selected" effect on the button
a quick suggestion from the perspective of color is that, the gradient for that "selected" effect, center of the button should be darker / more opaque; while the more outer, the otherwise.

Rest of the issue looked good.

**Comment by Emrys02** [comment]
@co01y4p an oversight on my end, it's been fixed.

**Comment by co01y4p** [comment]
@Emrys02 Very cool! now i saw the button color gradient had fixed!

a very quick check with you, there is an error popping out upon starting the screen

**Comment by co01y4p** [comment]
@Emrys02 Very cool! now i saw the button color gradient had fixed!

a very quick check with you, there is an error popping out upon starting the screen

Screenshot 2024-11-30 at 15 07 05


```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 328 pos 12: 'height > 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was:
    FittedBox FittedBox:file:/// ... ... /themarquis-app/lib/screens/home_screen.dart:41:17

...

The following RenderObject was being processed when the exception was fired: RenderFittedBox#6cafe relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(0.0<=w<=402.0, 0.0<=h<=Infinity)
    size: MISSING
    fit: contain
    alignment: Alignment.center
    textDirection: ltr
    child: RenderSemanticsAnnotations#f6442 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: <none> (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(402.0, 0.0)
        child: RenderImage#6a78f relayoutBoundary=up12 NEEDS-PAINT
            parentData: <none> (can use size)
            constraints: BoxConstraints(unconstrained)
            size: Size(402.0, 0.0)
            image: null
            width: 402.0
            fit: fill
            alignment: Alignment.center
            invertColors: false
            filterQuality: medium
RenderObject: RenderFittedBox#6cafe relayoutBoundary=up10 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
    constraints: BoxConstraints(0.0<=w<=402.0, 0.0<=h<=Infinity)
    size: MISSING
    fit: contain
    alignment: Alignment.center
    textDirection: ltr
    child: RenderSemanticsAnnotations#f6442 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: <none> (can use size)
        constraints: BoxConstraints(unconstrained)
        size: Size(402.0, 0.0)
        child: RenderImage#6a78f relayoutBoundary=up12 NEEDS-PAINT
            parentData: <none> (can use size)
            constraints: BoxConstraints(unconstrained)
            size: Size(402.0, 0.0)
            image: null
            width: 402.0
            fit: fill
            alignment: Alignment.center
            invertColors: false
            filterQuality: medium

```

**Comment by Emrys02** [comment]
@co01y4p could you confirm we're good

**Review by wms2537 — APPROVED** [review]
Everything working on my side.

**Pull request merged**
