### PR TITLE
made checkers board ui

### LINKED ISSUE #21: Implement `Checkers` : `game-play` section
## Issue Overview

Implement views of game logic/mechanism for checkers 

## Proposed Solutions or Ideas

- Implement this section based on provided [design](https://www.figma.com/design/bnuIyw9uQSTdWTJ273WUgn/The-Marquis-Mobile-App-Only-Dust?node-id=4554-6476&node-type=canvas&t=82lteI9XrWzdZc9q-0)
 
image

- There is no back-end or smart contracts, so no integration need it, Focus on implement and connect views
- This issue focuses on implementing the game play part.
  - CheckersGame (flame game wiring up all the components)
  - CheckersBoard Component
  - CheckersPin Component
  - UserStats Component
  - and other components that make up the game

### PR DESCRIPTION
**Pull request by akintewe**
### CheckersGame
- Main game controller that wires up all components
- Handles game state management and player turns
- Manages game dimensions and camera setup.    

### CheckersBoard
- Implements the 8x8 game board with alternating colors
- Handles piece placement and movement
- Manages piece selection and valid move highlighting
- Includes randomization feature for testing

##Images
Screenshot_1734374988

Screenshot_1734376332
Screenshot_1734376335
Screenshot_1734376339

Closes #21

### CODE REVIEW

**Comment by wms2537** [comment]
image
This is what I see

**Comment by wms2537** [comment]
With the following error
```[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: Null check operator used on a null value
#0      RiverpodGameMixin.onMount.<anonymous closure> (package:flame_riverpod/src/consumer.dart:149:16)
consumer.dart:149
#1      _RootZone.run (dart:async/zone.dart:1670:54)
zone.dart:1670
#2      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:247:18)
future_impl.dart:247
#3      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:872:39)
future_impl.dart:872
#4      Future._propagateToListeners (dart:async/future_impl.dart:928:11)
future_impl.dart:928
#5      Future._completeWithValue (dart:async/future_impl.dart:707:5)
future_impl.dart:707
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:777:7)
future_impl.dart:777
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
schedule_microtask.dart:40
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
schedule_microtask.dart:49
```

**Comment by akintewe** [comment]
> image This is what I see

Ill check out the error

**Comment by wms2537** [comment]
and also by looking at the screenshots you provided, the game is not vertically centered (also not horizontally centred on my side).

Also for the constants consider making a `constants.dart` inside the `checkers` directory to store the constants, including the flame game size, the colors, etc. (refer to Ludo)

**Comment by akintewe** [comment]
> and also by looking at the screenshots you provided, the game is not vertically centered (also not horizontally centred on my side).
> 
> Also for the constants consider making a `constants.dart` inside the `checkers` directory to store the constants, including the flame game size, the colors, etc. (refer to Ludo)

simulator_screenshot_6023ED42-D286-456B-95DB-737FF59E74EA
Fixed Please review

**Comment by wms2537** [comment]
Screenshot 2024-12-18 at 10 25 34 AM

**Comment by akintewe** [comment]
> Screenshot 2024-12-18 at 10 25 34 AM

done.  @wms2537 

Untitled


Please review

**Comment by wms2537** [comment]
image
The UI is not adaptive on screens of different sizes. This is how it looks on iPad

**Comment by akintewe** [comment]
@wms2537  Fixed the responsiveness to fit all screens   

Screenshot 2024-12-18 at 7 39 56 PM

Please review

**Comment by wms2537** [comment]
Ok, screen size is ok, but the left top back button is not working?

**Comment by akintewe** [comment]
> Ok, screen size is ok, but the left top back button is not working?

Oh its working, i tested it out

**Comment by akintewe** [comment]
@wms2537 made sure the back button works well, please verify

**Review by wms2537 — APPROVED** [review]
Working

**Pull request merged**
