### PR TITLE
Checkers : winning overlays section #28

### PR DESCRIPTION
**Pull request by Hoossayn**
## This PR:
-  Implements win/loose dialog
- Implements match result screen
- 

## Testing
For Testing purpose I have replace the `back button` in the checkers game screen to populate the overlay

## Demo video
https://www.loom.com/share/5c53d992ccc34c9ab7cf2e5bb4957d23

### CODE REVIEW

**Comment by wms2537** [comment]
The UI design is ok. The results screen add a lost queens and win pin count display as in figma.

**Comment by wms2537** [comment]
On the UI logic side, I would like it to be an overlay instead of a dialog, since it is hard to trigger a dialog display in the figma game. We might also need to migrate the create game screen to use the overlay method, so in the CheckersGame we will have a GameState 
```
enum PlayState { welcome, waiting, playing, finished }
```
We display different overlays based on different playstate (refer to the Ludo game)
```
overlayBuilderMap: {
        PlayState.welcome.name: (context, game) =>
            LudoWelcomeScreen(game: game),
        PlayState.waiting.name: (context, game) =>
            FourPlayerWaitingRoomScreen(game: game),
        PlayState.finished.name: (context, game) => MatchResultsScreen(
              game: game,
              session: ref.read(ludoSessionProvider)!,
            ),
      },
```

**Comment by wms2537** [comment]
image
The txn button on right top should show the list of transactions dialog.

**Comment by Hoossayn** [comment]
> image The txn button on right top should show the list of transactions dialog.

there's no UI yet for that if i'm not wrong. or @gianalarcon please point me to the list of Txn dialog if there's one. thanks

**Comment by gianalarcon** [comment]
> Txn dialog

Sorry for the inconvenience. For this game we dont have Txn dialog @wms2537

**Comment by wms2537** [comment]
oh ok

**Review by wms2537 — APPROVED** [review]
Working

**Pull request merged**
