### PR TITLE
feat: use starknet dart to get balance

### PR DESCRIPTION
**Pull request by JoE11-y**
Solves #3 

Changes made

1. Updated the get token balance function to use the starknet dart package.
2. Added Eth balance.
3. Added sepolia rpc endpoint as starknet-dart package hasn't been updated to support sepolia

Screenshot from 2024-11-24 22-43-12

### CODE REVIEW

**Comment by gianalarcon** [comment]
Hi @JoE11-y. Thanks for contribution. 
A small request pls
- Your PR should point to [starknet-dart](https://github.com/The-Marquis-Gaming/themarquis-app/tree/starknet-dart) branch
- Please provide an screenshot of the app with your solution

**Comment by co01y4p** [comment]
https://github.com/JoE11-y/themarquis-app/blob/d622f0d71a01ac3abae07d1e36908b6f2fe6665d/lib/providers/user.dart#L129C1-L130C1

our app is on StarkNet Sepolia, not StarkNet MainNet, try using the correct RPC endpoints.

**Comment by JoE11-y** [comment]
Oh okay. Was just following initial instructions of pointing the pr to the develop branch 

https://github.com/The-Marquis-Gaming/themarquis-app/issues/3#issuecomment-2491803808

**Comment by JoE11-y** [comment]
Screenshot from 2024-11-24 22-43-12

**Comment by wms2537** [comment]
Looks good to me.

**Review by wms2537 — APPROVED** [review]
Can merge

**Review by gianalarcon — APPROVED** [review]

**Pull request merged**
